# Generated by Django 5.1.4 on 2025-01-22 06:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_company_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(6200000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('position', models.CharField(choices=[('Manager', 'manger'), ('Software Developer', 'sd'), ('Project Leader', 'Pl')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='company', to='home.company')),
            ],
        ),
    ]
